### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by kfirfer** [topolvm/helm#1]
Hello all

Would like for reviews/suggestions/pull requests/ideas before chart release

Currently I have tested the chart on the following bare-metal Kubernetes cluster:

Kubernetes Version: `1.18.8`
Provisioned with `Kubeadm`
TopoLVM version `0.5.3`
Topology: `3 nodes master-master `
Nodes OS: `Linux nuc01 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
Scheduler as daemonset

Branch: `0.0.1`

**Comment by ymmt2005** [comment]
@binoue Do you want to take a look?

**Comment by kfirfer** [comment]
Initial release 0.0.1 committed
If there are any bugs/feature suggestion, you could freely open issues
Closing
