### ISSUE TITLE
auto generate self signed certificate without cert-manager

### ISSUE THREAD

**Issue by yanivroz** [topolvm/helm#8]
Feature request:
Add an option to automatically generate the self signed certificate without the need for cert-manager.
(Something like: `--set generate-self-signed-certificate=true|false`)
Default will be false and behavior remains the same as today.
When set to true some job will generate the key and certificate.
Something like:
```
openssl req -x509 -nodes -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -config <( \
  echo '[req]'; \
  echo 'distinguished_name = req_distinguished_name'; \
  echo 'x509_extensions = v3_req'; \
  echo 'prompt = no'; \
  echo '[req_distinguished_name]'; \
  echo 'CN = ca.selfsigned.topolvm'; \
  echo '[v3_req]'; \
  echo 'keyUsage = keyEncipherment, dataEncipherment'; \
  echo 'extendedKeyUsage = serverAuth'; \
  echo 'subjectAltName = @alt_names'; \
  echo '[alt_names]'; \
  echo 'DNS.1   = topolvm-controller'; \
  echo 'DNS.2   = topolvm-controller.topolvm-system'; \
  echo 'DNS.3   = topolvm-controller.topolvm-system.svc')
```
Then use the generated key.pem and cert.pem in the secret and MutatingWebhookConfiguration CRD as described [here](https://github.com/topolvm/topolvm/tree/master/deploy#optional-prepare-the-certificate-without-cert-manager)

**Comment by toshipp** [comment]
This repository has been deprecated. If you have any problems, please report an issue to topolvm/topolvm.
