### ISSUE TITLE
no matches for kind "CSIDriver" in version "storage.k8s.io/v1"

### ISSUE THREAD

**Issue by rootn9633** [topolvm/helm#9]
Deployment on a cluster with kubernetes v1.17.1 will fail with the error message:
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1"
```
This may be due to `CSIDriver` [not becoming GA until k8s v1.18](https://kubernetes-csi.github.io/docs/csi-driver-object.html)

Should the README be changed to require v1.18 and match the supported environments of the main topolvm repo?

**Comment by kfirfer** [comment]
Thanks
README have changed accordingly
